<?php
/**
 * Created by PhpStorm.
 * User: ducto
 * Date: 10/01/2018
 * Time: 11:31 SA
 */
defined('BASEPATH') OR exit('No direct script access allowed');

class Agency_model extends STEVEN_Model
{
  public function __construct()
  {
    parent::__construct();
    $this->table = 'agency';
    $this->column_order = array('id', 'id', 'name', 'title', 'created_time', 'updated_time'); //thiết lập cột sắp xếp
    $this->column_search = array('name', 'title'); //thiết lập cột search
    $this->order_default = array('created_time' => 'desc'); //cột sắp xếp mặc định
  }

  public function _where_custom($args = array())
  {
    parent::_where_custom($args); // TODO: Change the autogenerated stub
    extract($args);
    if(!empty($city_id)) $this->db->where("$this->table.city_id",$city_id);
    if(!empty($district_id)) $this->db->where("$this->table.district_id",$district_id);
    if (!empty($key_search)) {
      $this->db->group_start();
      $this->db->like("$this->table.title", trim($key_search));
      $this->db->or_like("$this->table.address", trim($key_search));
      $this->db->group_end();
    }
  }

  // Lấy đại lý gần mình nhất
  public function getAgenRecent($args = array(), $typeQuery = '')
  {
    $page = 1;
    $limit = 10;
    $lat = $log = $dist = 0;
    extract($args);
    if (!empty($typeQuery))
      $select = '1';
    else
      $select = array('A.*', '7912 * ASIN(SQRT( POWER(SIN((' . $lat . ' -
	ABS( 
		A.latitude)) * PI()/180 / 2),2) + COS(' . $lat . ' * PI()/180 ) * COS( 
		ABS
		(A.latitude) *  PI()/180) * POWER(SIN((' . $log . ' - A.longitude) *  PI()/180 / 2), 2) )
	) as distance');
    $this->db->select($select);
    $this->db->from("$this->table as A");
    $this->db->order_by('distance', 'ASC');
    if (empty($typeQuery)) {
      $offset = ($page - 1) * $limit;
      $this->db->limit($limit, $offset);
    }
    $query = $this->db->get();
    return $query->result();
  }
}